---
# User configuration
user_name: "{{ ansible_facts['user_id'] }}"
user_home: "{{ ansible_facts['env']['HOME'] }}"

# Homebrew
homebrew_taps: []

homebrew_formulae:
  - ansible
  - bat
  - fd
  - fish
  - fzf
  - gh
  - git
  - go-task
  - htop
  - jq
  - pre-commit
  - ripgrep
  - starship
  - tldr
  - tree
  - wget
  - zsh-autosuggestions
  - zsh-syntax-highlighting

homebrew_casks:
  - 1password
  - claude
  - claude-code
  - docker-desktop
  - evernote
  - font-fira-code-nerd-font
  - ghostty
  - google-drive
  - grammarly-desktop
  - monitorcontrol
  - mos
  - onedrive
  - raycast
  - rectangle
  - signal
  - slack
  - spotify
  - the-unarchiver
  - vivaldi
  - visual-studio-code


# Mac App Store (requires `mas` formula)
mas_apps: {}

mas_email: ""
mas_signin_dialog: false

# macOS Defaults
macos_defaults_computername: "Cedrics-MacBook-Pro"

# Dock
dock_apps: []
#  - /Applications/Safari.app
#  - /System/Applications/Mail.app
#  - /Applications/iTerm.app

dock_icon_size: 32
dock_autohide: false
dock_minimize_to_application: true
dock_show_recents: false

# Git
git_user_name: "Cedric GHIOT"
git_user_email: "8707686+cedsbe@users.noreply.github.com"
git_default_branch: "main"
git_editor: "vim"

# SSH (managed by 1Password agent)

# Shell
shell_fish_path: "{{ '/opt/homebrew' if ansible_facts['machine'] == 'arm64' else '/usr/local' }}/bin/fish"
